import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Importing Google Fonts with custom variables for use in the app
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
// Importing Google Fonts with custom variables for use in the app
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// Root layout component that wraps all pages and provides global styles and fonts  
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// Root layout component that wraps all pages and provides global styles and fonts
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
